# Generated by Django 3.2.12 on 2024-04-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100),
        ),
    ]
