# Generated by Django 3.2.12 on 2024-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='notes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='income',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
