# Generated by Django 3.2.12 on 2024-04-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_app', '0009_alter_income_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('duration_terms', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bill_date', models.DateField()),
                ('bill_amount', models.FloatField()),
                ('bill_cycle', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='budget_app.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
